# -*- coding: utf-8 -*-
"""MannMitra_final_14:30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dPWflOPvcxqwPxzpKvLrQc3JQ9_1hjg
"""

"""
================================================================================
 🧘  MannMitra  (मन-मित्र — "Friend of the Mind")
 An AI Wellness Companion for Students Facing Board Exams & Entrance Tests
 (NEET · JEE · CUET · CAT · GATE · UPSC)
================================================================================
HOW TO RUN IN GOOGLE COLAB (one cell, end-to-end):
────────────────────────────────────────────────────
1. Open a new Colab notebook.
2. Paste this entire cell and press Shift+Enter.
3. If no API key is found in environment/Colab secrets, you'll be prompted.
4. The app launches with a private Gradio link.
5. Click "🔑 Get API Key" in the UI to copy your key for later use.

================================================================================
"""

# ── 0. Silent auto-install ───────────────────────────────────────────────────
import subprocess, sys

def _install(pkg):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

for _pkg in ["groq", "gradio", "pillow", "requests", "matplotlib", "pytest"]:
    try:
        __import__(_pkg if _pkg != "pillow" else "PIL")
    except ImportError:
        print(f"📦 Installing {_pkg} …")
        _install(_pkg)

# ── 1. Imports ────────────────────────────────────────────────────────────────
import os
import re
import io
import random
import datetime
import getpass
from functools import lru_cache
from typing import List, Tuple, Optional, Any
import requests
import gradio as gr
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont
from groq import Groq

# ── 2. Configuration ──────────────────────────────────────────────────────────
PRIMARY_MODEL = "openai/gpt-oss-120b"
FALLBACK_MODEL = "openai/gpt-oss-20b"
MAX_TOKENS_JOURNAL = 2048   # enough for detailed response
MAX_TOKENS_CHAT = 1024      # short, conversational

# ── 3. Secure API key loader ─────────────────────────────────────────────────
def load_api_key() -> str:
    """
    Load Groq API key from environment variable, Colab userdata, or prompt.
    Returns the key as a string.
    """
    key = os.environ.get("GROQ_API_KEY", "")
    if key:
        return key

    try:
        from google.colab import userdata
        key = userdata.get("GROQ_API_KEY")
        if key:
            return key
    except Exception:
        pass

    key = getpass.getpass("🔑 Enter your Groq API Key: ").strip()
    if not key:
        raise ValueError("❌ No API key provided. Aborting.")
    return key

GROQ_API_KEY = load_api_key()
client = Groq(api_key=GROQ_API_KEY)

# ── 4. Core LLM caller (with fallback and reasoning hidden) ────────────────
def call_llm(
    messages: List[dict],
    temperature: float = 0.6,
    max_tokens: int = MAX_TOKENS_JOURNAL,
    model: str = PRIMARY_MODEL
) -> str:
    """
    Call the Groq LLM, hiding reasoning tokens and stripping think tags.
    """
    kwargs = dict(
        model=model,
        messages=messages,
        temperature=temperature,
        max_tokens=max_tokens,
    )
    try:
        response = client.chat.completions.create(
            **kwargs,
            extra_body={"reasoning_format": "hidden", "reasoning_effort": "low"},
        )
    except Exception:
        # Fallback if extra_body not supported (old API)
        response = client.chat.completions.create(**kwargs)

    content = response.choices[0].message.content or ""
    content = re.sub(r"<think>.*?</think>", "", content, flags=re.DOTALL).strip()
    return content

def call_llm_safe(
    messages: List[dict],
    temperature: float = 0.6,
    max_tokens: int = MAX_TOKENS_JOURNAL
) -> str:
    """Call LLM with automatic fallback to secondary model on rate limit / not found."""
    try:
        return call_llm(messages, temperature, max_tokens, model=PRIMARY_MODEL)
    except Exception as e:
        err = str(e).lower()
        if any(x in err for x in ("rate", "limit", "quota", "not found")):
            print(f"⚠️ Primary model unavailable — falling back to {FALLBACK_MODEL}")
            return call_llm(messages, temperature, max_tokens, model=FALLBACK_MODEL)
        raise

# ── 5. Crisis detection (deterministic safety layer) ────────────────────────
CRISIS_KEYWORDS = [
    "suicide", "kill myself", "end my life", "end it all", "want to die",
    "no reason to live", "self harm", "self-harm", "hurt myself",
    "better off dead", "can't go on", "cant go on", "give up on life",
    "no point in living", "i want to disappear",
]

def detect_crisis(text: str) -> bool:
    """Return True if any crisis keyword appears in the text."""
    t = (text or "").lower()
    return any(k in t for k in CRISIS_KEYWORDS)

CRISIS_RESPONSE = """### 💛 You are not alone — please reach out right now

What you've written matters, and it deserves more support than an app can give.
Please talk to a trusted adult, family member, or teacher today — and consider
calling one of these **free, confidential, 24×7 helplines**:

| Helpline | Number |
|---|---|
| 🇮🇳 **Tele MANAS** (Govt. of India, Ministry of Health) | **14416** / 1-800-891-4416 |
| 🇮🇳 **KIRAN** (Govt. of India, Ministry of Social Justice) | **1800-599-0019** |
| **iCall** (TISS) | 9152987821 |
| **Vandrevala Foundation** | 1860-266-2345 |

You matter more than any rank, score, or exam. Please make the call. 💛"""

# ── 6. System prompts ─────────────────────────────────────────────────────────
SYSTEM_PROMPT_JOURNAL = """
You are MannMitra, an empathetic AI wellness companion built for Indian
students preparing for high-stakes exams (NEET, JEE, CUET, CAT, GATE, UPSC, board exams).

You receive: the exam they're preparing for, a self-rated mood score (1-10), and a free-text
journal entry about their day or thoughts.

Your job, in order:
1. Look PAST the surface words for the hidden emotional trigger the student didn't explicitly
   name (e.g. comparison anxiety, fear of disappointing parents, sleep debt, imposter syndrome,
   burnout, perfectionism, social isolation). Name it gently, never clinically.
2. Validate their feelings in one warm sentence — never dismissive.
3. Give ONE specific coping strategy tied to exactly what they wrote — not generic advice.
4. Give ONE short adaptive mindfulness or breathing exercise (60-120 seconds), with clear,
   numbered steps, tailored to their specific stressor.
5. Close with one line of genuine, specific encouragement (not a cliché).

Never diagnose a mental health condition. Never compare the student to others. Never sound
like a textbook. Write like a warm, wise senior who genuinely cares.

When it genuinely fits the stressor (restlessness, poor sleep, low energy, racing thoughts,
difficulty focusing), you may suggest a short daily Surya Namaskar (Sun Salutation) practice
as part of your strategy — it's a well-known holistic practice that calms the mind and body
together. Don't force it into every response; only mention it when it truly fits.

Do not reveal any reasoning, analysis steps, or <think> tags — output ONLY the final response,
using exactly these section headers and nothing before or after them:

##MOOD SNAPSHOT##
(one short empathetic line reflecting their mood back to them)

##THE HIDDEN PATTERN##
(2-3 sentences naming the underlying trigger you noticed)

##YOUR PERSONALISED STRATEGY##
(one concrete, specific action — tied to their exact words)

##60-SECOND RESET##
(a short numbered breathing/mindfulness exercise, 3-5 steps)

##ONE THING TO REMEMBER##
(one line of sincere encouragement)
"""

CHAT_SYSTEM_PROMPT = """
You are MannMitra, a warm, always-available AI wellness companion for
Indian students preparing for competitive exams (NEET, JEE, CUET, CAT, GATE, UPSC) and board
exams. You talk like a caring, emotionally intelligent senior — never clinical, never preachy,
never robotic. Keep replies conversational and concise (under 120 words) unless the student
clearly wants more depth. You can offer coping strategies, quick mindfulness exercises, study-
stress perspective, and encouragement. You never diagnose conditions, never shame the student,
and never compare them to other students. If a student seems to be spiralling, gently slow
down and check in on their wellbeing before talking about exams again. When it genuinely fits,
you may suggest a short daily Surya Namaskar (Sun Salutation) practice — many students find it
calms restlessness and sharpens focus before a study session.

Do not reveal reasoning or <think> tags — reply only with your final spoken response.
"""

# ── 7. Mood history and plot ──────────────────────────────────────────────────
MOOD_HISTORY: List[dict] = []

def mood_plot() -> plt.Figure:
    """Generate a plot of mood history."""
    fig, ax = plt.subplots(figsize=(6.4, 3.1), dpi=130)
    if not MOOD_HISTORY:
        ax.text(0.5, 0.5, "Your mood trend will appear here\nafter your first check-in",
                ha="center", va="center", fontsize=11, color="#888")
        ax.axis("off")
    else:
        xs = list(range(1, len(MOOD_HISTORY) + 1))
        ys = [m["mood"] for m in MOOD_HISTORY]
        ax.plot(xs, ys, marker="o", linewidth=2.5, color="#2f7a5c")
        ax.fill_between(xs, ys, 0, alpha=0.08, color="#2f7a5c")
        ax.set_ylim(0, 10.5)
        ax.set_xticks(xs)
        ax.set_xlabel("Check-in #")
        ax.set_ylabel("Mood (1-10)")
        ax.set_title("Your Mood Journey", fontsize=12, fontweight="bold")
        ax.grid(alpha=0.25)
    fig.tight_layout()
    return fig

EXAMS = ["JEE (Main/Advanced)", "NEET", "CUET", "CAT", "GATE", "UPSC",
         "Class 10/12 Boards", "Other"]

# ── 8. Journal analysis ──────────────────────────────────────────────────────
def analyze_journal(exam: str, mood_score: int, journal_text: str) -> Tuple[str, plt.Figure]:
    """Process the journal entry and return the response and updated mood plot."""
    if not journal_text or not journal_text.strip():
        return "✍️ Write a few honest lines about your day first — even two sentences help.", mood_plot()

    MOOD_HISTORY.append({
        "time": datetime.datetime.now().strftime("%H:%M:%S"),
        "exam": exam,
        "mood": float(mood_score),
    })

    if detect_crisis(journal_text):
        return CRISIS_RESPONSE, mood_plot()

    user_msg = f"Exam: {exam}\nMood (1-10): {mood_score}\nJournal entry:\n{journal_text}"
    try:
        reply = call_llm_safe(
            [{"role": "system", "content": SYSTEM_PROMPT_JOURNAL},
             {"role": "user", "content": user_msg}],
            temperature=0.6,
            max_tokens=MAX_TOKENS_JOURNAL,
        )
    except Exception as e:
        reply = (f"⚠️ Couldn't reach the AI service right now ({e}).\n"
                 "Please check your Groq API key / internet connection and try again.")
    return reply, mood_plot()

# ── 9. Chat companion ──────────────────────────────────────────────────────────
def chat_respond(user_message: str, history: List[dict]) -> Tuple[List[dict], str]:
    """Handle chat messages and return updated history and cleared input."""
    history = history or []
    if not user_message or not user_message.strip():
        return history, ""

    if detect_crisis(user_message):
        history = history + [{"role": "user", "content": user_message},
                             {"role": "assistant", "content": CRISIS_RESPONSE}]
        return history, ""

    messages = [{"role": "system", "content": CHAT_SYSTEM_PROMPT}]
    messages.extend(history[-16:])
    messages.append({"role": "user", "content": user_message})

    try:
        reply = call_llm_safe(messages, temperature=0.7, max_tokens=MAX_TOKENS_CHAT)
    except Exception as e:
        reply = f"⚠️ Couldn't reach the AI service right now ({e}). Please try again."

    history = history + [{"role": "user", "content": user_message},
                         {"role": "assistant", "content": reply}]
    return history, ""

# ── 10. Quotes engine ──────────────────────────────────────────────────────────
QUOTES_DEFAULT = [
    {"text": "The mind is everything. What you think, you become.", "author": "Swami Vivekananda"},
    {"text": "Arise, awake, and stop not till the goal is reached.", "author": "Swami Vivekananda"},
    {"text": "Know thyself.", "author": "Socrates"},
    {"text": "The unexamined life is not worth living, but a life examined too harshly is not worth living either — be gentle with yourself.", "author": "Inspired by Socrates"},
    {"text": "It is during our darkest moments that we must focus to see the light.", "author": "Aristotle"},
    {"text": "We are what we repeatedly do. Excellence, then, is not an act but a habit.", "author": "Aristotle"},
    {"text": "You have power over your mind, not outside events. Realise this, and you will find strength.", "author": "Marcus Aurelius"},
    {"text": "Talk to yourself once in a day, otherwise you may miss meeting an excellent person in this world.", "author": "A. P. J. Abdul Kalam"},
    {"text": "Dream, dream, dream. Dreams transform into thoughts, and thoughts result in action.", "author": "A. P. J. Abdul Kalam"},
    {"text": "It does not matter how slowly you go, as long as you do not stop.", "author": "Confucius"},
    {"text": "Fall seven times, stand up eight.", "author": "Japanese Proverb"},
    {"text": "Whatever happened, happened for the good. Whatever is happening, is happening for the good. Whatever will happen, will also happen for the good.", "author": "Bhagavad Gita"},
]

MY_OWN_QUOTES = []   # Add custom quotes here (backend only)
ALL_QUOTES = QUOTES_DEFAULT + MY_OWN_QUOTES

def format_quote(q: dict) -> str:
    return f"### ❝ {q['text']} ❞\n\n— **{q['author']}**"

@lru_cache(maxsize=1)
def cached_random_quote() -> str:
    """Return a randomly selected quote (cached so it stays for the session)."""
    return format_quote(random.choice(ALL_QUOTES))

def random_quote() -> str:
    """Return a random quote (used for 'Show Today's Quote')."""
    return format_quote(random.choice(ALL_QUOTES))

# ── 11. Surya Namaskar daily tracker ──────────────────────────────────────────
PRACTICE_LOG: set = set()

def mark_surya_namaskar_done() -> str:
    """Record today's practice and return a streak message."""
    today = datetime.date.today()
    PRACTICE_LOG.add(today.isoformat())
    streak, d = 0, today
    while d.isoformat() in PRACTICE_LOG:
        streak += 1
        d -= datetime.timedelta(days=1)
    if streak <= 1:
        return "✅ Logged for today — that's a great start. 🌞"
    return f"✅ Logged for today! 🔥 {streak}-day streak — keep it going!"

# ── 12. Motivational image generator ──────────────────────────────────────────
INSTITUTES = ["IIT Bombay", "IIT Kharagpur", "IIT Kanpur", "IIT Madras", "IIT Delhi",
              "AIIMS", "IIM Ahmedabad", "Custom (type below)"]

def _load_font(size: int) -> ImageFont:
    """Load a TrueType font or fallback to default."""
    for name in ("DejaVuSans-Bold.ttf", "DejaVuSans.ttf"):
        try:
            return ImageFont.truetype(name, size)
        except Exception:
            continue
    return ImageFont.load_default()

def generate_motivation_image(
    institute: str,
    custom_name: str,
    days_done: int,
    days_total: int
) -> Image.Image:
    """Generate a motivational image with progress bar."""
    name = (custom_name.strip() if institute == "Custom (type below)" and custom_name else institute)
    try:
        days_done = max(0, int(days_done))
    except Exception:
        days_done = 0
    try:
        days_total = max(1, int(days_total))
    except Exception:
        days_total = 1
    pct = min(100, int(round(100 * days_done / days_total)))

    prompt = (
        f"cinematic warm golden-hour digital painting, a determined young Indian student in "
        f"casual clothes climbing the final stone steps toward a grand, ornate academic gateway "
        f"with classical pillars, the words '{name}' engraved on the archway above, soft sunrise "
        f"light, sense of hope courage and near-achievement, inspirational poster style, highly "
        f"detailed, painterly, no readable extra text, no logos"
    )
    seed = random.randint(1, 999999)
    url = ("https://image.pollinations.ai/prompt/" + requests.utils.quote(prompt)
           + f"?width=1024&height=683&nologo=true&seed={seed}")

    try:
        resp = requests.get(url, timeout=45)
        img = Image.open(io.BytesIO(resp.content)).convert("RGB")
    except Exception:
        # Fallback placeholder
        img = Image.new("RGB", (1024, 683), (255, 247, 230))
        d = ImageDraw.Draw(img)
        d.text((40, 40), "(Image service unreachable — showing placeholder card)",
               fill=(120, 90, 40), font=_load_font(26))

    draw = ImageDraw.Draw(img)
    bar_x, bar_y, bar_w, bar_h = 56, img.height - 86, img.width - 112, 30
    draw.rounded_rectangle([bar_x, bar_y, bar_x + bar_w, bar_y + bar_h],
                           radius=15, fill=(255, 255, 255))
    fill_w = max(30, int(bar_w * pct / 100))
    draw.rounded_rectangle([bar_x, bar_y, bar_x + fill_w, bar_y + bar_h],
                           radius=15, fill=(255, 140, 0))
    caption = f"You're {pct}% of the way to {name} -- just a little closer!"
    draw.text((bar_x, bar_y - 46), caption, fill=(25, 25, 25), font=_load_font(28))
    return img

# ── 13. Test suite (runs automatically before launch) ────────────────────────
def test_core_functions():
    """Run a suite of unit tests to verify critical logic."""
    print("\n🧪 Running core function tests...")

    # Test crisis detection
    assert detect_crisis("I want to kill myself") is True
    assert detect_crisis("I feel sad") is False
    assert detect_crisis("I can't go on") is True
    print("  ✅ detect_crisis")

    # Test quote formatting
    q = {"text": "Test", "author": "Me"}
    assert "Test" in format_quote(q)
    assert "Me" in format_quote(q)
    print("  ✅ format_quote")

    # Test mood plot creation (just ensure no exception)
    fig = mood_plot()
    assert fig is not None
    plt.close(fig)
    print("  ✅ mood_plot")

    # Test Surya Namaskar logging (non-destructive)
    # We just call it and check it returns a string
    result = mark_surya_namaskar_done()
    assert isinstance(result, str)
    print("  ✅ mark_surya_namaskar_done")

    print("✅ All tests passed!\n")

# Run tests
test_core_functions()

# ── 14. Custom CSS – Indian flag sunrise theme ──────────────────────────────
CSS = """
.gradio-container {max-width: 1180px !important; margin: auto; position: relative; z-index: 2;}

/* Indian flag sunrise gradient */
body {
    background: radial-gradient(ellipse at 50% 40%,
        #FFD700 0%, #FFA500 15%, #FF8C00 30%, #FF9933 45%,
        #FFFFFF 60%, #E8F5E9 75%, #2E7D32 100%);
    background-attachment: fixed;
    min-height: 100vh;
    margin: 0;
    padding: 0;
    position: relative;
}

/* Glowing sun */
body::before {
    content: "";
    position: fixed;
    top: 35%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 500px;
    height: 500px;
    background: radial-gradient(circle, rgba(255, 215, 0, 0.35) 0%, rgba(255, 165, 0, 0.15) 50%, transparent 75%);
    border-radius: 50%;
    pointer-events: none;
    z-index: 0;
    filter: blur(10px);
}

/* Sanskrit watermark */
body::after {
    content: "🌅 योगः कर्मसु कौशलम्";
    white-space: pre;
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 140px;
    opacity: 0.08;
    font-family: 'Times New Roman', serif;
    text-align: center;
    line-height: 1.3;
    color: #1a1a1a;
    pointer-events: none;
    z-index: 0;
    letter-spacing: 4px;
    font-weight: bold;
    text-shadow: 0 0 30px rgba(255,255,255,0.6);
}

/* Hero banner */
#hero {
    background: linear-gradient(120deg, #FF9933 0%, #FFFFFF 50%, #138808 100%);
    padding: 22px 26px;
    border-radius: 18px;
    margin-bottom: 14px;
    box-shadow: 0 4px 20px rgba(0,0,0,0.15);
    border: 1px solid rgba(255,255,255,0.5);
    position: relative;
    z-index: 3;
    backdrop-filter: blur(2px);
}

#hero h1 {
    color: #000000;
    margin: 0 0 2px 0;
    text-shadow: 0 2px 12px rgba(255,255,255,0.9);
    font-weight: 800;
    font-size: 2.2rem;
}

#hero .subtitle {
    color: #1a2a3a;
    margin: 0;
    font-size: 18px;
    font-weight: 700;
    letter-spacing: 1px;
}
#hero .subtitle em {
    font-style: normal;
    background: rgba(255,255,255,0.5);
    padding: 2px 16px;
    border-radius: 30px;
    backdrop-filter: blur(4px);
}
#hero p {
    margin: 6px 0 0 0;
    color: #1a2a3a;
    font-size: 14px;
    font-weight: 600;
}

/* Accessibility */
*:focus-visible {
    outline: 3px solid #138808 !important;
    outline-offset: 2px;
}
button { min-height: 44px !important; }

.quote-box textarea, .quote-box {
    font-size: 17px !important;
    background: rgba(255,255,255,0.80) !important;
    backdrop-filter: blur(8px);
    border-radius: 12px;
    border: 1px solid rgba(255,153,51,0.3);
    padding: 20px;
}

footer { visibility: hidden; }
#api-key-box textarea {
    font-family: monospace !important;
    background: #f0f0f0 !important;
    border: 2px solid #FF9933 !important;
}
"""

# ── 15. Build Gradio UI ──────────────────────────────────────────────────────
with gr.Blocks(css=CSS, title="MannMitra — AI Wellness Companion") as demo:

    gr.HTML("""
    <div id="hero">
        <h1>🧘 MannMitra — मन-मित्र</h1>
        <p class="subtitle">
            <em>🌅 योगः कर्मसु कौशलम् — Excellence in work is Yoga</em>
        </p>
        <p>
            An always-available AI wellness companion for students preparing for
            NEET · JEE · CUET · CAT · GATE · UPSC and Board Exams.
        </p>
    </div>
    """)

    # API Key reveal
    with gr.Row():
        with gr.Column(scale=1):
            api_btn = gr.Button("🔑 Get API Key", variant="primary", elem_id="api-reveal-btn")
        with gr.Column(scale=3):
            api_output = gr.Textbox(
                label="Your Groq API Key (copy for later use)",
                value=GROQ_API_KEY,
                visible=False,
                elem_id="api-key-box",
                interactive=False,
            )
    api_btn.click(fn=lambda: gr.update(visible=True), outputs=[api_output])

    gr.Markdown("---")

    with gr.Tabs():
        # Tab 1: Daily Check-in
        with gr.Tab("📝 Daily Check-in"):
            gr.Markdown("### Tell MannMitra how today really felt — even two honest lines help.")
            with gr.Row():
                with gr.Column(scale=1):
                    exam_dd = gr.Dropdown(EXAMS, value="JEE (Main/Advanced)", label="Which exam are you preparing for?")
                    mood_sl = gr.Slider(1, 10, value=5, step=1, label="How is your mood right now? (1 = very low, 10 = great)")
                    journal_tb = gr.Textbox(lines=7, label="Your journal entry",
                                            placeholder="e.g. Mock test went badly again today. I keep comparing myself to my friend who scored higher. I feel like I'm letting my parents down...")
                    analyze_btn = gr.Button("🔎 Get My Personalised Support", variant="primary")
                with gr.Column(scale=1):
                    analysis_out = gr.Markdown(label="MannMitra's response")
            gr.Markdown("---")
            mood_chart = gr.Plot(label="Your Mood Journey")

        # Tab 2: Chat
        with gr.Tab("💬 Talk to MannMitra"):
            gr.Markdown("### Your always-available companion — talk about anything on your mind.")
            try:
                chatbot = gr.Chatbot(type="messages", height=420, avatar_images=(None, None), allow_tags=False)
            except TypeError:
                chatbot = gr.Chatbot(height=420, avatar_images=(None, None), allow_tags=False)
            with gr.Row():
                chat_in = gr.Textbox(placeholder="Type how you're feeling, or ask for a coping tip…",
                                     scale=5, show_label=False)
                chat_btn = gr.Button("Send 💬", scale=1, variant="primary")

        # Tab 3: Almost There
        with gr.Tab("🎯 Almost There"):
            gr.Markdown("### See how far you've already come — visualised.")
            with gr.Row():
                with gr.Column(scale=1):
                    inst_dd = gr.Dropdown(INSTITUTES, value="IIT Bombay", label="Your dream institute")
                    custom_tb = gr.Textbox(label="If 'Custom', type the name here", placeholder="e.g. AIIMS Delhi")
                    days_done_n = gr.Number(value=60, label="Days of preparation completed", precision=0)
                    days_total_n = gr.Number(value=180, label="Total preparation days planned", precision=0)
                    img_btn = gr.Button("🌅 Generate My Motivation", variant="primary")
                with gr.Column(scale=1):
                    motivation_img = gr.Image(label="Just a little closer…", type="pil")

        # Tab 4: Surya Namaskar
        with gr.Tab("🌞 Surya Namaskar"):
            gr.Markdown("""
### Start your day with Surya Namaskar (Sun Salutation)

Surya Namaskar is a gentle, centuries-old 12-step yoga sequence that takes just
10–15 minutes — one of the simplest daily habits a student can build during exam season.

**Why it's worth doing every morning:**
- 🧘 Calms an anxious mind and eases exam-time stress
- 🎯 Sharpens focus and concentration before a study session
- 💪 Builds the physical stamina needed for long hours at the desk
- 😴 Improves sleep quality
- ⚡ Lifts energy naturally — no caffeine needed

📖 [Read the full benefits guide — The Art of Living](https://www.artofliving.org/in-en/yoga/beginners/sun-salutation-benefits)

*(Learn the postures under guidance the first few times — a teacher or a trusted video
helps you get the form right, especially if you have any existing health condition.)*
""")
            sn_btn = gr.Button("✅ I completed my Surya Namaskar today", variant="primary")
            sn_status = gr.Markdown()

        # Tab 5: Quote of the Day
        with gr.Tab("🌟 Quote of the Day"):
            gr.Markdown("### A moment of wisdom, every day.")
            quote_md = gr.Markdown(cached_random_quote(), elem_classes=["quote-box"])
            new_quote_btn = gr.Button("✨ Show Today's Quote", variant="primary")

    gr.Markdown("""
---
⚠️ **MannMitra is a supportive companion, not a substitute for professional mental-health
care.** If you or someone you know is in distress, please call **Tele MANAS — 14416**
or **KIRAN — 1800-599-0019** (both free, confidential, 24×7, Government of India).
""")

    # ── Event bindings ──────────────────────────────────────────────────────
    analyze_btn.click(
        fn=analyze_journal,
        inputs=[exam_dd, mood_sl, journal_tb],
        outputs=[analysis_out, mood_chart]
    )

    chat_btn.click(
        fn=chat_respond,
        inputs=[chat_in, chatbot],
        outputs=[chatbot, chat_in]
    )
    chat_in.submit(
        fn=chat_respond,
        inputs=[chat_in, chatbot],
        outputs=[chatbot, chat_in]
    )

    img_btn.click(
        fn=generate_motivation_image,
        inputs=[inst_dd, custom_tb, days_done_n, days_total_n],
        outputs=[motivation_img]
    )

    new_quote_btn.click(
        fn=random_quote,
        outputs=[quote_md]
    )

    sn_btn.click(
        fn=mark_surya_namaskar_done,
        outputs=[sn_status]
    )

# ── 16. Launch ──────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 70)
    print("  🧘  MannMitra — AI Wellness Companion for Exam Warriors")
    print("  🌅 योगः कर्मसु कौशलम् — Excellence in work is Yoga")
    print("=" * 70)
    print("  🔑 API Key loaded securely.")
    print("  ✅ All core tests passed.")
    print("  🌐 Launching Gradio app… (link below)\n")
    demo.queue()  # enables better handling of concurrent requests
    demo.launch(share=True, show_error=True, quiet=False)

