# -*- coding: utf-8 -*-
"""MannMitra_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dPWflOPvcxqwPxzpKvLrQc3JQ9_1hjg
"""

"""
================================================================================
 🧘  MannMitra  (मन-मित्र — "Friend of the Mind")
 An AI Wellness Companion for Students Facing Board Exams & Entrance Tests
 (NEET · JEE · CUET · CAT · GATE · UPSC)
================================================================================
HOW TO RUN IN GOOGLE COLAB (one cell, end-to-end):
────────────────────────────────────────────────────
1. Open a new Colab notebook (colab.research.google.com).
2. Paste this entire file into ONE code cell and press ▶ (Shift+Enter).
3. The app starts immediately – NO API KEY PROMPT.
4. Click the "🔑 Get API Key" button in the UI to reveal the key.
5. A private Gradio link appears – click it for the live demo.

================================================================================
"""

# ── 0. Silent auto-install ───────────────────────────────────────────────────
import subprocess, sys

def _install(pkg):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

for _pkg in ["groq", "gradio", "pillow", "requests", "matplotlib"]:
    try:
        __import__(_pkg if _pkg != "pillow" else "PIL")
    except ImportError:
        print(f"📦 Installing {_pkg} …")
        _install(_pkg)

# ── 1. Imports ────────────────────────────────────────────────────────────────
import os, re, io, random, datetime, textwrap
import requests
import gradio as gr
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont
from groq import Groq

# ── 2. API key – HARDCODED (LIVE) – NO PROMPT ──────────────────────────────
# 🔑 This key is embedded so the demo runs instantly.
#    It is hidden in the UI and only shown when the "Get API Key" button is clicked.
GROQ_API_KEY = "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"

# (Optional fallback for Colab secrets, but not needed since we hardcoded it)
if not GROQ_API_KEY:
    try:
        from google.colab import userdata
        GROQ_API_KEY = userdata.get("GROQ_API_KEY") or ""
    except Exception:
        pass

if not GROQ_API_KEY:
    raise ValueError(
        "❌ GROQ_API_KEY is not set. Please edit the notebook and put your "
        "Groq API key in the GROQ_API_KEY variable before running."
    )

client = Groq(api_key=GROQ_API_KEY)

PRIMARY_MODEL  = "openai/gpt-oss-120b"   # current Groq production flagship
FALLBACK_MODEL = "openai/gpt-oss-20b"    # lighter / higher rate-limit
MAX_TOKENS     = 4096

# ── 3. LLM caller — reasoning fully hidden ──────────────────────────────────
def call_llm(messages, temperature=0.6, max_tokens=MAX_TOKENS, model=PRIMARY_MODEL):
    kwargs = dict(model=model, messages=messages, temperature=temperature,
                  max_tokens=max_tokens)
    try:
        response = client.chat.completions.create(
            **kwargs,
            extra_body={"reasoning_format": "hidden", "reasoning_effort": "low"},
        )
    except Exception:
        response = client.chat.completions.create(**kwargs)

    content = response.choices[0].message.content or ""
    content = re.sub(r"<think>.*?</think>", "", content, flags=re.DOTALL).strip()
    return content


def call_llm_safe(messages, temperature=0.6, max_tokens=MAX_TOKENS):
    try:
        return call_llm(messages, temperature, max_tokens, model=PRIMARY_MODEL)
    except Exception as e:
        err = str(e).lower()
        if "rate" in err or "limit" in err or "quota" in err or "not found" in err:
            print(f"⚠️  Primary model unavailable — falling back to {FALLBACK_MODEL}")
            return call_llm(messages, temperature, max_tokens, model=FALLBACK_MODEL)
        raise


# ── 4. Deterministic safety layer ────────────────────────────────────────────
CRISIS_KEYWORDS = [
    "suicide", "kill myself", "end my life", "end it all", "want to die",
    "no reason to live", "self harm", "self-harm", "hurt myself",
    "better off dead", "can't go on", "cant go on", "give up on life",
    "no point in living", "i want to disappear",
]

def detect_crisis(text: str) -> bool:
    t = (text or "").lower()
    return any(k in t for k in CRISIS_KEYWORDS)

CRISIS_RESPONSE = """### 💛 You are not alone — please reach out right now

What you've written matters, and it deserves more support than an app can give.
Please talk to a trusted adult, family member, or teacher today — and consider
calling one of these **free, confidential, 24×7 helplines**:

| Helpline | Number |
|---|---|
| 🇮🇳 **Tele MANAS** (Govt. of India, Ministry of Health) | **14416** / 1-800-891-4416 |
| 🇮🇳 **KIRAN** (Govt. of India, Ministry of Social Justice) | **1800-599-0019** |
| **iCall** (TISS) | 9152987821 |
| **Vandrevala Foundation** | 1860-266-2345 |

You matter more than any rank, score, or exam. Please make the call. 💛"""

# ── 5. System prompts ─────────────────────────────────────────────────────────
SYSTEM_PROMPT_JOURNAL = """You are MannMitra, an empathetic AI wellness companion built for Indian
students preparing for high-stakes exams (NEET, JEE, CUET, CAT, GATE, UPSC, board exams).

You receive: the exam they're preparing for, a self-rated mood score (1-10), and a free-text
journal entry about their day or thoughts.

Your job, in order:
1. Look PAST the surface words for the hidden emotional trigger the student didn't explicitly
   name (e.g. comparison anxiety, fear of disappointing parents, sleep debt, imposter syndrome,
   burnout, perfectionism, social isolation). Name it gently, never clinically.
2. Validate their feelings in one warm sentence — never dismissive.
3. Give ONE specific coping strategy tied to exactly what they wrote — not generic advice.
4. Give ONE short adaptive mindfulness or breathing exercise (60-120 seconds), with clear,
   numbered steps, tailored to their specific stressor.
5. Close with one line of genuine, specific encouragement (not a cliché).

Never diagnose a mental health condition. Never compare the student to others. Never sound
like a textbook. Write like a warm, wise senior who genuinely cares.

When it genuinely fits the stressor (restlessness, poor sleep, low energy, racing thoughts,
difficulty focusing), you may suggest a short daily Surya Namaskar (Sun Salutation) practice
as part of your strategy — it's a well-known holistic practice that calms the mind and body
together. Don't force it into every response; only mention it when it truly fits.

Do not reveal any reasoning, analysis steps, or <think> tags — output ONLY the final response,
using exactly these section headers and nothing before or after them:

##MOOD SNAPSHOT##
(one short empathetic line reflecting their mood back to them)

##THE HIDDEN PATTERN##
(2-3 sentences naming the underlying trigger you noticed)

##YOUR PERSONALISED STRATEGY##
(one concrete, specific action — tied to their exact words)

##60-SECOND RESET##
(a short numbered breathing/mindfulness exercise, 3-5 steps)

##ONE THING TO REMEMBER##
(one line of sincere encouragement)
"""

CHAT_SYSTEM_PROMPT = """You are MannMitra, a warm, always-available AI wellness companion for
Indian students preparing for competitive exams (NEET, JEE, CUET, CAT, GATE, UPSC) and board
exams. You talk like a caring, emotionally intelligent senior — never clinical, never preachy,
never robotic. Keep replies conversational and concise (under 120 words) unless the student
clearly wants more depth. You can offer coping strategies, quick mindfulness exercises, study-
stress perspective, and encouragement. You never diagnose conditions, never shame the student,
and never compare them to other students. If a student seems to be spiralling, gently slow
down and check in on their wellbeing before talking about exams again. When it genuinely fits,
you may suggest a short daily Surya Namaskar (Sun Salutation) practice — many students find it
calms restlessness and sharpens focus before a study session.

Do not reveal reasoning or <think> tags — reply only with your final spoken response."""

# ── 6. Mood history ──────────────────────────────────────────────────────────
MOOD_HISTORY = []   # list of dicts: time, exam, mood

def mood_plot():
    fig, ax = plt.subplots(figsize=(6.4, 3.1), dpi=130)
    if not MOOD_HISTORY:
        ax.text(0.5, 0.5, "Your mood trend will appear here\nafter your first check-in",
                ha="center", va="center", fontsize=11, color="#888")
        ax.axis("off")
    else:
        xs = list(range(1, len(MOOD_HISTORY) + 1))
        ys = [m["mood"] for m in MOOD_HISTORY]
        ax.plot(xs, ys, marker="o", linewidth=2.5, color="#2f7a5c")
        ax.fill_between(xs, ys, 0, alpha=0.08, color="#2f7a5c")
        ax.set_ylim(0, 10.5)
        ax.set_xticks(xs)
        ax.set_xlabel("Check-in #")
        ax.set_ylabel("Mood (1-10)")
        ax.set_title("Your Mood Journey", fontsize=12, fontweight="bold")
        ax.grid(alpha=0.25)
    fig.tight_layout()
    return fig

# ── 7. Journal analysis ──────────────────────────────────────────────────────
EXAMS = ["JEE (Main/Advanced)", "NEET", "CUET", "CAT", "GATE", "UPSC",
         "Class 10/12 Boards", "Other"]

def analyze_journal(exam, mood_score, journal_text):
    if not journal_text or not journal_text.strip():
        return "✍️ Write a few honest lines about your day first — even two sentences help.", mood_plot()

    MOOD_HISTORY.append({
        "time": datetime.datetime.now().strftime("%H:%M:%S"),
        "exam": exam, "mood": float(mood_score),
    })

    if detect_crisis(journal_text):
        return CRISIS_RESPONSE, mood_plot()

    user_msg = f"Exam: {exam}\nMood (1-10): {mood_score}\nJournal entry:\n{journal_text}"
    try:
        reply = call_llm_safe(
            [{"role": "system", "content": SYSTEM_PROMPT_JOURNAL},
             {"role": "user", "content": user_msg}],
            temperature=0.6,
        )
    except Exception as e:
        reply = (f"⚠️ Couldn't reach the AI service right now ({e}).\n"
                  "Please check your Groq API key / internet connection and try again.")
    return reply, mood_plot()

# ── 8. Conversational companion ──────────────────────────────────────────────
def chat_respond(user_message, history):
    history = history or []
    if not user_message or not user_message.strip():
        return history, ""

    if detect_crisis(user_message):
        history = history + [{"role": "user", "content": user_message},
                              {"role": "assistant", "content": CRISIS_RESPONSE}]
        return history, ""

    messages = [{"role": "system", "content": CHAT_SYSTEM_PROMPT}]
    messages.extend(history[-16:])
    messages.append({"role": "user", "content": user_message})

    try:
        reply = call_llm_safe(messages, temperature=0.7)
    except Exception as e:
        reply = f"⚠️ Couldn't reach the AI service right now ({e}). Please try again."

    history = history + [{"role": "user", "content": user_message},
                          {"role": "assistant", "content": reply}]
    return history, ""

# ── 9. Quotes engine (No UI for adding quotes) ──────────────────────────────
QUOTES_DEFAULT = [
    {"text": "The mind is everything. What you think, you become.", "author": "Swami Vivekananda"},
    {"text": "Arise, awake, and stop not till the goal is reached.", "author": "Swami Vivekananda"},
    {"text": "Know thyself.", "author": "Socrates"},
    {"text": "The unexamined life is not worth living, but a life examined too harshly is not worth living either — be gentle with yourself.", "author": "Inspired by Socrates"},
    {"text": "It is during our darkest moments that we must focus to see the light.", "author": "Aristotle"},
    {"text": "We are what we repeatedly do. Excellence, then, is not an act but a habit.", "author": "Aristotle"},
    {"text": "You have power over your mind, not outside events. Realise this, and you will find strength.", "author": "Marcus Aurelius"},
    {"text": "Talk to yourself once in a day, otherwise you may miss meeting an excellent person in this world.", "author": "A. P. J. Abdul Kalam"},
    {"text": "Dream, dream, dream. Dreams transform into thoughts, and thoughts result in action.", "author": "A. P. J. Abdul Kalam"},
    {"text": "It does not matter how slowly you go, as long as you do not stop.", "author": "Confucius"},
    {"text": "Fall seven times, stand up eight.", "author": "Japanese Proverb"},
    {"text": "Whatever happened, happened for the good. Whatever is happening, is happening for the good. Whatever will happen, will also happen for the good.", "author": "Bhagavad Gita"},
]

# You can add more quotes here privately (backend only)
MY_OWN_QUOTES = []
QUOTES = QUOTES_DEFAULT + MY_OWN_QUOTES

def format_quote(q):
    return f"### ❝ {q['text']} ❞\n\n— **{q['author']}**"

def random_quote():
    return format_quote(random.choice(QUOTES))

# ── 9b. Surya Namaskar daily-practice tracker ────────────────────────────────
PRACTICE_LOG = set()

def mark_surya_namaskar_done():
    today = datetime.date.today()
    PRACTICE_LOG.add(today.isoformat())
    streak, d = 0, today
    while d.isoformat() in PRACTICE_LOG:
        streak += 1
        d -= datetime.timedelta(days=1)
    if streak <= 1:
        return "✅ Logged for today — that's a great start. 🌞"
    return f"✅ Logged for today! 🔥 {streak}-day streak — keep it going!"

# ── 10. Generative "Almost There" motivational imagery ───────────────────────
INSTITUTES = ["IIT Bombay", "IIT Kharagpur", "IIT Kanpur", "IIT Madras", "IIT Delhi",
              "AIIMS", "IIM Ahmedabad", "Custom (type below)"]

def _load_font(size):
    for name in ("DejaVuSans-Bold.ttf", "DejaVuSans.ttf"):
        try:
            return ImageFont.truetype(name, size)
        except Exception:
            continue
    return ImageFont.load_default()

def generate_motivation_image(institute, custom_name, days_done, days_total):
    name = (custom_name.strip() if institute == "Custom (type below)" and custom_name else institute)
    try:
        days_done = max(0, int(days_done))
    except Exception:
        days_done = 0
    try:
        days_total = max(1, int(days_total))
    except Exception:
        days_total = 1
    pct = min(100, int(round(100 * days_done / days_total)))

    prompt = (
        f"cinematic warm golden-hour digital painting, a determined young Indian student in "
        f"casual clothes climbing the final stone steps toward a grand, ornate academic gateway "
        f"with classical pillars, the words '{name}' engraved on the archway above, soft sunrise "
        f"light, sense of hope courage and near-achievement, inspirational poster style, highly "
        f"detailed, painterly, no readable extra text, no logos"
    )
    seed = random.randint(1, 999999)
    url = ("https://image.pollinations.ai/prompt/" + requests.utils.quote(prompt)
           + f"?width=1024&height=683&nologo=true&seed={seed}")

    try:
        resp = requests.get(url, timeout=45)
        img = Image.open(io.BytesIO(resp.content)).convert("RGB")
    except Exception:
        img = Image.new("RGB", (1024, 683), (255, 247, 230))
        d = ImageDraw.Draw(img)
        d.text((40, 40), "(Image service unreachable — showing placeholder card)",
                fill=(120, 90, 40), font=_load_font(26))

    draw = ImageDraw.Draw(img)
    bar_x, bar_y, bar_w, bar_h = 56, img.height - 86, img.width - 112, 30
    draw.rounded_rectangle([bar_x, bar_y, bar_x + bar_w, bar_y + bar_h],
                            radius=15, fill=(255, 255, 255))
    fill_w = max(30, int(bar_w * pct / 100))
    draw.rounded_rectangle([bar_x, bar_y, bar_x + fill_w, bar_y + bar_h],
                            radius=15, fill=(255, 140, 0))
    caption = f"You're {pct}% of the way to {name} -- just a little closer!"
    draw.text((bar_x, bar_y - 46), caption, fill=(25, 25, 25), font=_load_font(28))
    return img

# ── 11. Custom CSS — Indian tricolour theme ──────────────────────────────────
CSS = """
.gradio-container {max-width: 1180px !important; margin: auto;}

/* Full-page subtle tricolour gradient overlay */
body {
    background: linear-gradient(135deg, rgba(255, 153, 51, 0.08) 0%,
                                rgba(255, 255, 255, 0.10) 50%,
                                rgba(19, 136, 8, 0.08) 100%);
    background-attachment: fixed;
}

/* Hero banner – bold tricolour with glow */
#hero {
    background: linear-gradient(120deg, #FF9933 0%, #FFFFFF 50%, #138808 100%);
    padding: 22px 26px;
    border-radius: 18px;
    margin-bottom: 14px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.08);
    border: 1px solid rgba(255,255,255,0.3);
}

#hero h1 {
    color: #10331f;
    margin: 0 0 4px 0;
    text-shadow: 0 2px 4px rgba(255,255,255,0.3);
}
#hero p {
    color: #234;
    margin: 0;
    font-size: 15px;
    font-weight: 500;
}

/* Quote box styling – semi‑transparent with blur */
.quote-box textarea, .quote-box {
    font-size: 17px !important;
    background: rgba(255,255,255,0.70) !important;
    backdrop-filter: blur(4px);
    border-radius: 12px;
    border: 1px solid rgba(255,153,51,0.2);
    padding: 20px;
}

/* Hide Gradio footer */
footer {visibility: hidden}

/* Style for the API key reveal area */
#api-key-box textarea {
    font-family: monospace !important;
    background: #f0f0f0 !important;
    border: 2px solid #FF9933 !important;
}
"""

# ── 12. Gradio app ────────────────────────────────────────────────────────────
with gr.Blocks(css=CSS, title="MannMitra — AI Wellness Companion") as demo:

    gr.HTML(
        """<div id="hero">
        <h1>🧘 MannMitra — मन-मित्र</h1>
        <p>An always-available AI wellness companion for students preparing for
        NEET · JEE · CUET · CAT · GATE · UPSC and Board Exams.</p>
        </div>"""
    )

    # ── API Key reveal section ──────────────────────────────────────────────
    with gr.Row():
        with gr.Column(scale=1):
            api_btn = gr.Button("🔑 Get API Key", variant="primary")
        with gr.Column(scale=3):
            api_output = gr.Textbox(
                label="Your Groq API Key (copy this for your own notebook)",
                value=GROQ_API_KEY,
                visible=False,
                elem_id="api-key-box",
                interactive=False,
            )
    api_btn.click(
        fn=lambda: gr.update(visible=True),
        outputs=[api_output]
    )

    gr.Markdown("---")

    with gr.Tabs():

        # ---------- TAB 1 : Daily Check-in ----------
        with gr.Tab("📝 Daily Check-in"):
            gr.Markdown("### Tell MannMitra how today really felt — even two honest lines help.")
            with gr.Row():
                with gr.Column(scale=1):
                    exam_dd   = gr.Dropdown(EXAMS, value="JEE (Main/Advanced)", label="Which exam are you preparing for?")
                    mood_sl   = gr.Slider(1, 10, value=5, step=1, label="How is your mood right now? (1 = very low, 10 = great)")
                    journal_tb = gr.Textbox(lines=7, label="Your journal entry",
                                             placeholder="e.g. Mock test went badly again today. I keep comparing myself to my friend who scored higher. I feel like I'm letting my parents down...")
                    analyze_btn = gr.Button("🔎 Get My Personalised Support", variant="primary")
                with gr.Column(scale=1):
                    analysis_out = gr.Markdown(label="MannMitra's response")
            gr.Markdown("---")
            mood_chart = gr.Plot(label="Your Mood Journey")

        # ---------- TAB 2 : Chat companion ----------
        with gr.Tab("💬 Talk to MannMitra"):
            gr.Markdown("### Your always-available companion — talk about anything on your mind.")
            try:
                chatbot = gr.Chatbot(type="messages", height=420, avatar_images=(None, None), allow_tags=False)
            except TypeError:
                chatbot = gr.Chatbot(height=420, avatar_images=(None, None), allow_tags=False)
            with gr.Row():
                chat_in  = gr.Textbox(placeholder="Type how you're feeling, or ask for a coping tip…",
                                       scale=5, show_label=False)
                chat_btn = gr.Button("Send 💬", scale=1, variant="primary")

        # ---------- TAB 3 : Almost There ----------
        with gr.Tab("🎯 Almost There"):
            gr.Markdown("### See how far you've already come — visualised.")
            with gr.Row():
                with gr.Column(scale=1):
                    inst_dd   = gr.Dropdown(INSTITUTES, value="IIT Bombay", label="Your dream institute")
                    custom_tb = gr.Textbox(label="If 'Custom', type the name here", placeholder="e.g. AIIMS Delhi")
                    days_done_n  = gr.Number(value=60, label="Days of preparation completed", precision=0)
                    days_total_n = gr.Number(value=180, label="Total preparation days planned", precision=0)
                    img_btn = gr.Button("🌅 Generate My Motivation", variant="primary")
                with gr.Column(scale=1):
                    motivation_img = gr.Image(label="Just a little closer…", type="pil")

        # ---------- TAB 4 : Surya Namaskar ----------
        with gr.Tab("🌞 Surya Namaskar"):
            gr.Markdown("""
### Start your day with Surya Namaskar (Sun Salutation)

Surya Namaskar is a gentle, centuries-old 12-step yoga sequence that takes just
10–15 minutes — one of the simplest daily habits a student can build during exam season.

**Why it's worth doing every morning:**
- 🧘 Calms an anxious mind and eases exam-time stress
- 🎯 Sharpens focus and concentration before a study session
- 💪 Builds the physical stamina needed for long hours at the desk
- 😴 Improves sleep quality
- ⚡ Lifts energy naturally — no caffeine needed

📖 [Read the full benefits guide — The Art of Living](https://www.artofliving.org/in-en/yoga/beginners/sun-salutation-benefits)

*(Learn the postures under guidance the first few times — a teacher or a trusted video
helps you get the form right, especially if you have any existing health condition.)*
""")
            sn_btn = gr.Button("✅ I completed my Surya Namaskar today", variant="primary")
            sn_status = gr.Markdown()

        # ---------- TAB 5 : Quote of the Day (Simplified) ----------
        with gr.Tab("🌟 Quote of the Day"):
            gr.Markdown("### A moment of wisdom, every day.")
            quote_md = gr.Markdown(random_quote(), elem_classes=["quote-box"])
            new_quote_btn = gr.Button("✨ Show Today's Quote", variant="primary")

    gr.Markdown("""
---
⚠️ **MannMitra is a supportive companion, not a substitute for professional mental-health
care.** If you or someone you know is in distress, please call **Tele MANAS — 14416**
or **KIRAN — 1800-599-0019** (both free, confidential, 24×7, Government of India).
""")

    # ── wire events ──────────────────────────────────────────────────────────
    analyze_btn.click(fn=analyze_journal, inputs=[exam_dd, mood_sl, journal_tb],
                       outputs=[analysis_out, mood_chart])

    chat_btn.click(fn=chat_respond, inputs=[chat_in, chatbot], outputs=[chatbot, chat_in])
    chat_in.submit(fn=chat_respond, inputs=[chat_in, chatbot], outputs=[chatbot, chat_in])

    img_btn.click(fn=generate_motivation_image,
                   inputs=[inst_dd, custom_tb, days_done_n, days_total_n],
                   outputs=[motivation_img])

    new_quote_btn.click(fn=random_quote, outputs=[quote_md])
    sn_btn.click(fn=mark_surya_namaskar_done, outputs=[sn_status])

# ── 13. Launch ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 70)
    print("  🧘  MannMitra — AI Wellness Companion for Exam Warriors")
    print("=" * 70)
    print("  🔑 API Key loaded (hidden by default).")
    print("  🌐 Warming things up – your private link will appear in a few seconds…\n")
    demo.launch(share=True, show_error=True, quiet=False)

